export type Env = { GOOGLE_SERVICE_ACCOUNT_EMAIL: string; GOOGLE_PRIVATE_KEY: string; GOOGLE_SHEET_ID: string; SESSION_SECRET: string };
const tabs: Record<string,string[]> = { users:['id','full_name','email','password_hash','active','created_at','updated_at','last_login_at'], roles:['id','name','description','protected','permissions_csv'], user_roles:['user_id','role_id'], departments:['id','name_en','name_ar','active'], locations:['id','name_en','name_ar','active'], vacancies:['id','vacancy_no','role_title','department_id','location_id','status','current_stage','progress_percentage','hiring_number','owner_id','start_date','target_end_date','created_at','updated_at'], vacancy_recruitment_details:['vacancy_id','start_date','end_date','actual_end_date','workload_planning_and_job_analysis','on_hand_number','hiring_number','company_department_strategy_json','department','location','budget_setup_amount','job_description','job_ads_writing','hiring_team_user_ids_json','selected_channels_json','updated_at','updated_by'], candidates:['id','full_name','role_title','stage','score','source','owner_id','created_at','updated_at'], notifications:['id','user_id','vacancy_id','message','read','created_at'] };
export const json=(data:any,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
export async function readBody(req:Request){try{return await req.json()}catch{return {}}}
async function b64url(buf:ArrayBuffer){return btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
export async function sign(value:string,secret:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return `${value}.${await b64url(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value)))}`}
export async function verify(cookie:string|undefined,secret:string){const token=cookie?.match(/sros_session=([^;]+)/)?.[1]; if(!token)return null; const [v]=token.split('.'); return token===await sign(v,secret)?JSON.parse(atob(v)):null}
export async function hashPassword(password:string,salt=crypto.randomUUID()){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:120000,hash:'SHA-256'},key,256);return `pbkdf2$120000$${salt}$${await b64url(bits)}`}
export async function checkPassword(password:string,stored:string){const [, , salt, hash]=stored.split('$');return (await hashPassword(password,salt)).endsWith(`$${hash}`)}
async function token(env:Env){const now=Math.floor(Date.now()/1000);const header=await b64url(new TextEncoder().encode(JSON.stringify({alg:'RS256',typ:'JWT'})));const claim=await b64url(new TextEncoder().encode(JSON.stringify({iss:env.GOOGLE_SERVICE_ACCOUNT_EMAIL,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600})));const pem=env.GOOGLE_PRIVATE_KEY.replace(/\\n/g,'\n');const bin=Uint8Array.from(atob(pem.replace(/-----[^-]+-----|\s/g,'')),c=>c.charCodeAt(0));const key=await crypto.subtle.importKey('pkcs8',bin,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=await b64url(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(`${header}.${claim}`)));const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:`${header}.${claim}.${sig}`})});return (await r.json() as any).access_token}
export async function sheet(env:Env,tab:string){const access=await token(env);const base=`https://sheets.googleapis.com/v4/spreadsheets/${env.GOOGLE_SHEET_ID}/values`;const headers={Authorization:`Bearer ${access}`,'Content-Type':'application/json'};return {async rows(){const r=await fetch(`${base}/${tab}!A:Z`,{headers});const vals=((await r.json()) as any).values||[];const head=vals[0]||tabs[tab];return vals.slice(1).map((row:string[])=>Object.fromEntries(head.map((h:string,i:number)=>[h,row[i]||''])));},async append(obj:any){const row=tabs[tab].map(h=>typeof obj[h]==='object'?JSON.stringify(obj[h]):obj[h]??'');await fetch(`${base}/${tab}!A:Z:append?valueInputOption=USER_ENTERED`,{method:'POST',headers,body:JSON.stringify({values:[row]})});},async update(id:string,obj:any){const rows=await this.rows();const idx=rows.findIndex((r:any)=>(r.id||r.vacancy_id)===id);if(idx<0)throw new Error('Record not found');const merged={...rows[idx],...obj};await fetch(`${base}/${tab}!A${idx+2}:Z${idx+2}?valueInputOption=USER_ENTERED`,{method:'PUT',headers,body:JSON.stringify({values:[tabs[tab].map(h=>merged[h]??'')]})});}}}
export async function requireUser(req:Request,env:Env,permission?:string){const s=await verify(req.headers.get('Cookie')||'',env.SESSION_SECRET);if(!s)throw new Response('Unauthorized',{status:401});if(permission && !s.permissions?.includes('*') && !s.permissions?.includes(permission))throw new Response('Forbidden',{status:403});return s}
