const stages=['CV Screening','Phone Screening','First Interview','Second Interview','Offer Sent'];
const statuses=['Draft','Pending Manager Approval','Approved','Returned for Modification','In Progress','Filled','Cancelled'];
const icons={Dashboard:'▦',Vacancies:'▣',Candidates:'◉',Approvals:'✓',Reports:'⌁',Admin:'⚙',Settings:'◌'};
let user=null,page='Dashboard';
const can=p=>user?.permissions?.includes('*')||user?.permissions?.includes(p);
async function api(path,init={}){const r=await fetch('/api'+path,{credentials:'include',headers:{'Content-Type':'application/json',...(init.headers||{})},...init});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'Request failed');return r.json()}
function el(html){const t=document.createElement('template');t.innerHTML=html.trim();return t.content.firstChild}
function toast(msg){document.querySelector('main')?.prepend(el(`<div class="toast">${msg}</div>`))}
function login(){document.body.innerHTML='<main class="login"><form class="login-card"><div class="brand">Salahly <span>Recruitment OS</span></div><p>Sign in with your ATS account.</p><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" required></label><div class="error" hidden></div><button>Sign in</button></form></main>';document.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{user=(await api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(f))})).user;render()}catch(err){const box=document.querySelector('.error');box.hidden=false;box.textContent=err.message}}}
function shell(){const nav=[['Dashboard','vacancies.view'],['Vacancies','vacancies.view'],['Candidates','candidates.view'],['Approvals','approvals.view'],['Reports','reports.view'],['Admin','users.view'],['Settings','settings.view']].filter(n=>can(n[1]));document.body.innerHTML=`<aside><div class="logo">Salahly OS</div>${nav.map(n=>`<button class="${page===n[0]?'active':''}" data-page="${n[0]}"><span>${icons[n[0]]}</span>${n[0]}</button>`).join('')}</aside><section class="app"><header><div>⌕ <span>Search recruiting workspace</span></div><button class="ghost">🔔</button>${can('vacancies.create')?'<button data-page="Vacancies">New vacancy</button>':''}<button id="logout" class="ghost">Logout</button></header><main><h1>Loading…</h1></main></section>`;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.querySelector('#logout').onclick=async()=>{await api('/auth/logout',{method:'POST'});user=null;login()};content()}
function table(rows,actions=false){return `<div class="table"><table><thead><tr>${['Vacancy No','Role','Department','Status','Progress','Actions'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${r.vacancy_no||''}</td><td>${r.role_title||''}</td><td>${r.department_id||''}</td><td><span class="badge">${r.status||''}</span></td><td><div class="bar"><i style="width:${r.progress_percentage||0}%"></i></div></td><td>${actions?'<button>View</button> <button>Edit</button> <button class="danger">Delete</button>':''}</td></tr>`).join(''):'<tr><td colspan="6">No records found.</td></tr>'}</tbody></table></div>`}
async function content(){const main=document.querySelector('main');if(page==='Dashboard'){let d={openVacancies:0,pendingApprovals:0,activeCandidates:0,avgTimeToFill:0,vacancies:[]};try{d=await api('/reports/summary')}catch{}main.innerHTML=`<h1>Dashboard</h1><div class="cards">${[['Open vacancies',d.openVacancies],['Pending approvals',d.pendingApprovals],['Active candidates',d.activeCandidates],['Avg. time to fill',d.avgTimeToFill+' days']].map(c=>`<div class="card"><small>${c[0]}</small><strong>${c[1]}</strong></div>`).join('')}</div>${table(d.vacancies)}`}
else if(page==='Vacancies'){let rows=[];try{rows=(await api('/vacancies')).vacancies}catch{}main.innerHTML=`<h1>Vacancies</h1><div class="toolbar"><input id="q" placeholder="Search role, vacancy no, department"><select id="status"><option value="">All statuses</option>${statuses.map(s=>`<option>${s}</option>`).join('')}</select>${can('vacancies.create')?'<button id="create">Create vacancy</button>':''}</div><div id="vacancyTable">${table(rows,true)}</div>`;document.querySelector('#create')&&(document.querySelector('#create').onclick=async()=>{const role_title=prompt('Role title?');if(role_title){await api('/vacancies',{method:'POST',body:JSON.stringify({role_title,department_id:'dept-ops',location_id:'loc-riyadh',hiring_number:1,start_date:new Date().toISOString().slice(0,10),target_end_date:new Date().toISOString().slice(0,10)})});toast('Vacancy created')}})}
else if(page==='Candidates'){let rows=[];try{rows=(await api('/candidates')).candidates}catch{}main.innerHTML=`<h1>Candidates</h1><div class="kanban">${stages.map(s=>`<section><h3>${s}</h3>${rows.filter(c=>c.stage===s).map(c=>`<article class="candidate"><b>${c.full_name}</b><span>${c.role_title}</span><small>${c.source} • ${c.score}%</small></article>`).join('')}</section>`).join('')}</div>`}
else if(page==='Approvals')main.innerHTML='<h1>Approvals</h1><p>Pending Manager Approval inbox with Approve and Return actions for authorized users.</p>';
else if(page==='Reports')main.innerHTML='<h1>Reports</h1><p>Funnel, time-to-hire, source, and workload indicators are calculated from Google Sheets.</p><button onclick="window.print()">Export / Print</button>';
else if(page==='Admin')main.innerHTML='<h1>Admin</h1><p>Manage users, roles, and permissions. API protects the last active Super Admin and protected roles.</p>';
else main.innerHTML='<h1>Settings</h1><p>Manage departments, locations, recruitment stages, and email templates. Placeholder areas are intentionally clear for future setup.</p>'}
function render(){user?shell():login()}api('/me').then(r=>{user=r.user;render()}).catch(login);
